# Generated by Django 6.0.5 on 2026-05-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='desc',
            field=models.BooleanField(default=False),
        ),
    ]
